"""
Arcade WireGuard Invite System — One-click VPN invites for friends.
Friends get a WireGuard config file, connect, and join game servers
without any port forwarding on their end.
"""

import subprocess
import ipaddress
import secrets
from pathlib import Path
from typing import Optional

WG_CONFIG = "/etc/wireguard/wg0.conf"
WG_KEYS_DIR = "/etc/wireguard"
WG_SUBNET = "10.100.0.0/24"
WG_SERVER_IP = "10.100.0.1"
WG_LISTEN_PORT = 51820
DDNS_HOSTNAME = "1n1.freemyip.com"
INVITES_DIR = Path(__file__).parent.parent / "invites"


def _run(cmd: str, timeout: int = 10) -> tuple[int, str]:
    """Run a local command."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)
    return result.returncode, result.stdout.strip()


def generate_keypair() -> tuple[str, str]:
    """Generate a WireGuard keypair."""
    rc, privkey = _run("wg genkey")
    rc, pubkey = _run(f"echo '{privkey}' | wg pubkey")
    return privkey, pubkey


def get_server_pubkey() -> str:
    """Get the WireGuard server's public key."""
    rc, key = _run(f"cat {WG_KEYS_DIR}/server-public.key 2>/dev/null")
    if rc != 0 or not key:
        rc, key = _run("wg show wg0 public-key 2>/dev/null")
    return key


def get_next_client_ip() -> str:
    """Find the next available IP in the WireGuard subnet."""
    rc, output = _run("wg show wg0 allowed-ips 2>/dev/null")
    used_ips = set()
    used_ips.add("10.100.0.1")  # Server

    for line in output.split("\n"):
        parts = line.split("\t")
        if len(parts) >= 2:
            for cidr in parts[1].split(","):
                cidr = cidr.strip()
                if cidr and "/" in cidr:
                    ip = cidr.split("/")[0]
                    used_ips.add(ip)

    network = ipaddress.ip_network(WG_SUBNET)
    for addr in network.hosts():
        ip = str(addr)
        if ip not in used_ips:
            return ip

    raise RuntimeError("No available IPs in WireGuard subnet")


def create_invite(player_name: str, steam_id: str = "") -> dict:
    """
    Create a WireGuard invite for a friend.
    Returns the client config and adds the peer to the server.
    """
    INVITES_DIR.mkdir(parents=True, exist_ok=True)

    # Generate client keypair
    client_privkey, client_pubkey = generate_keypair()
    client_ip = get_next_client_ip()
    server_pubkey = get_server_pubkey()

    if not server_pubkey:
        raise RuntimeError("Cannot read WireGuard server public key")

    # Generate preshared key for extra security
    rc, psk = _run("wg genpsk")

    # Client config
    client_config = f"""# Arcade VPN — Earth C-137
# Player: {player_name}
# Steam ID: {steam_id}
# Generated by Quartermaster

[Interface]
PrivateKey = {client_privkey}
Address = {client_ip}/24
DNS = 149.112.121.20, 9.9.9.9

[Peer]
PublicKey = {server_pubkey}
PresharedKey = {psk}
Endpoint = {DDNS_HOSTNAME}:{WG_LISTEN_PORT}
AllowedIPs = 10.100.0.0/24, 10.0.0.131/32
PersistentKeepalive = 25
"""

    # Add peer to server
    add_cmd = (
        f"sudo wg set wg0 peer {client_pubkey} "
        f"preshared-key <(echo '{psk}') "
        f"allowed-ips {client_ip}/32"
    )
    rc, output = _run(f"bash -c \"{add_cmd}\"")

    if rc != 0:
        # Try alternative method
        _run(f"echo '{psk}' > /tmp/wg_psk_tmp && "
             f"sudo wg set wg0 peer {client_pubkey} "
             f"preshared-key /tmp/wg_psk_tmp "
             f"allowed-ips {client_ip}/32 && "
             f"rm /tmp/wg_psk_tmp")

    # Save to WireGuard config for persistence
    peer_block = f"""
# {player_name} ({steam_id})
[Peer]
PublicKey = {client_pubkey}
PresharedKey = {psk}
AllowedIPs = {client_ip}/32
"""
    _run(f"echo '{peer_block}' | sudo tee -a {WG_CONFIG} > /dev/null")

    # Save invite file
    safe_name = player_name.replace(" ", "_").lower()
    invite_path = INVITES_DIR / f"{safe_name}.conf"
    invite_path.write_text(client_config)

    return {
        "player_name": player_name,
        "steam_id": steam_id,
        "client_ip": client_ip,
        "config_path": str(invite_path),
        "config": client_config,
        "connect_instructions": (
            f"1. Install WireGuard: https://www.wireguard.com/install/\n"
            f"2. Import the attached .conf file\n"
            f"3. Activate the tunnel\n"
            f"4. Join game servers at 10.0.0.131 (or use 1n1.freemyip.com)\n"
            f"\nYour VPN IP: {client_ip}"
        ),
    }


def list_invites() -> list:
    """List all created invites."""
    INVITES_DIR.mkdir(parents=True, exist_ok=True)
    invites = []
    for f in INVITES_DIR.glob("*.conf"):
        content = f.read_text()
        name = f.stem.replace("_", " ").title()
        # Extract IP from config
        ip = ""
        for line in content.split("\n"):
            if line.startswith("Address"):
                ip = line.split("=")[1].strip().split("/")[0]
                break
        invites.append({"name": name, "ip": ip, "file": str(f)})
    return invites


def revoke_invite(player_name: str) -> bool:
    """Remove a peer from WireGuard."""
    safe_name = player_name.replace(" ", "_").lower()
    invite_path = INVITES_DIR / f"{safe_name}.conf"

    if not invite_path.exists():
        return False

    # Read the config to get the public key
    content = invite_path.read_text()
    # We need the pubkey from the server side — read from wg0.conf
    # For now, just remove the invite file and note it needs manual wg peer removal
    invite_path.unlink()
    return True
